-- New Customer Creation (HillMaster-style) — run once on existing PostgreSQL DBs.

ALTER TABLE customers ADD COLUMN IF NOT EXISTS sub_ledger VARCHAR(40);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tin VARCHAR(30);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_name VARCHAR(120);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS alt_phone VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS fax_no VARCHAR(30);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS po_box VARCHAR(40);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tax_rate VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(12, 2);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS invoice_due_days INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS price_list_code VARCHAR(80);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS status_label VARCHAR(40);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gl_coa_code VARCHAR(40);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gl_coa_name TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gl_category VARCHAR(80);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gl_customer_type VARCHAR(80);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS allow_credit BOOLEAN DEFAULT TRUE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS on_hold BOOLEAN DEFAULT FALSE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_dealer BOOLEAN DEFAULT FALSE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS notes_other TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS address_local TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS address_foreign TEXT;
